name: flutter_login_ui
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_pw_validator: ^1.2.1
  flutter:
    sdk: flutter
  tmdb_api:
  google_fonts:
  direct_select: "^1.0.3"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter



flutter_icons:
android: "launcher_icon"
ios: true
image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/logos/logostaj21.png
   - assets/logos/logolifeassistant.png
  


   
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf